### ISSUE TITLE
Update for 3.1.0 ?

### ISSUE THREAD

**Issue by JulienBier** [mquan/lavish#18]
Hi,
Do you have any plan to make it compatible with bootstrap 3.1.0 ? 
However thanks for this nice tool !

**Comment by mquan** [comment]
Sorry, there's a bug in the less compiler that prevents this from happening, I may have to switch to sass

**Comment by marclaporte** [comment]
Latest stable Bootstrap support would be awesome:
http://blog.getbootstrap.com/2015/03/16/bootstrap-3-3-4-released/

Thanks!

**Comment by mquan** [comment]
bootstrap 3.3.4 is now supported
