### ISSUE TITLE
Grey scale images cause error

### ISSUE THREAD

**Issue by noconstruct** [mquan/lavish#21]
http://www.lavishbootstrap.com/?utf8=%E2%9C%93&image_url=http%3A%2F%2Fimg.wallpaperstock.net%3A81%2Fgreyscale-moon-wallpapers_4148_1680x1050.jpg&commit=Go+Lavish

returns

"We're sorry, but something went wrong."

**Comment by mquan** [comment]
I couldn't access the image there, may be the url is private and can only be accessed from authenticated account?

**Comment by ruudsilvrants** [comment]
Hey,
Got the same error with an grayscale image, this image is sure to be accesible without any authentication

**Comment by mquan** [comment]
Lavish needs at least 5 distinct colors so images with less colors won't work

**Comment by mquan** [comment]
This is now fixed
