### ISSUE TITLE
.modal position off screen

### ISSUE THREAD

**Issue by LouisMilotte** [mquan/lavish#22]
On line 4954~ for media selector screen width 768px

.modal-dialog is positioned to the left by 50%. This by default pushes navigation based triggers off screen (if right navigation). The default should be left:0; to resolve. The purpose of a modal is to bring absolute attention to the event; thus, overlapping all content.

**Comment by mquan** [comment]
I'm not sure if this is introduced by lavish. Lavish only alters the colors in variables section and does not touch anything else.

**Comment by LouisMilotte** [comment]
This does happen in lavish as the CSS declaration above is within the lavish generated file.

**Comment by mquan** [comment]
Yes, lavish generates the css/less file but it only touches the color variables. So whatever unexpected behavior that isn't color related is a possible bug in bootstrap 3.0
