### ISSUE TITLE
Change font size and generate config.json

### ISSUE THREAD

**Issue by vinigarcia87** [mquan/lavish#23]
Please, add a feature to change the font-size. Sometimes, we don't want 14px.
Generate config.json with all the configurations, like the official bootstrap website does, would be nice too.
thanks

**Comment by mquan** [comment]
there are just too many customizable variables to add so I hesitate to add this option. Plus the current Bootstrap version isn't compatible with Lavish anymore. You can take the customized less output from bootstrap and apply only the color changes at the top of lavish output to achieve what you want. There are only 5 or 6 color variables that are changed.

**Comment by marclaporte** [comment]
It would be really cool to have a few things to customize :-)

And have a random value rendered on each page load, like http://www.strangebanana.com/

Thanks!
