### ISSUE TITLE
Can't find how to generate Bootstrap 3.3.4 css

### ISSUE THREAD

**Issue by vartagg** [mquan/lavish#27]
Hi! Thanks for your project! Tell me please how to generate css for Bootstrap 3.3.4? Is this functionality available on the site? There is a text about it on the main page: "Now compatible with Bootstrap 3.3.4 and Foundation 5.5.2(NEW)".

**Comment by visualsbysina** [comment]
I'm pretty sure the code it natively outputs is already bootstrap 3.3.4? Not sure though, currently bootstrap is at 3.3.5

**Comment by mquan** [comment]
You get the code in Step 3: Get the code
