### ISSUE TITLE
LESS file?

### ISSUE THREAD

**Issue by marc-gist** [mquan/lavish#29]
What happened to the less file output? I haven't used your great program/site in some time, but I got a LESS file from it before and need to again.
can you bring it back? 
Thanks!

**Comment by jaysavage83** [comment]
They use sass instead of less. sass is a better preprocessor.

**Comment by mquan** [comment]
Like @JayGreentree said the project generates sass file since Bootstrap support sass a few years back

**Comment by marc-gist** [comment]
I know they use sass and I guess Bootstrap "supports" it; but it mainly uses LESS. I'm not really looking to debate LESS vs SASS... Lavish is fantastic, and used to support LESS file output.  I would like to see that again.
does Lavish require SASS (i.e. does something that LESS simply Can't do?).

Thanks!

**Comment by marc-gist** [comment]
"While Bootstrap is built on Less ..."
http://getbootstrap.com/css/#sass 
So they have to port Bootstrap to SASS.

**Comment by mquan** [comment]
The bootstrap version that Lavish used to support is very old. Even if Lavish supports LESS you wouldn't easily just get the output and apply to whatever you're using.

But you can always create LESS yourself.

Just to give you an idea, Lavish modifies the 7 colors in varianles.sass and then concatenate all the sass files to generate the whole bootstrap.sass then compile to CSS. So you could try to get the bootstrap.less file and change the 7colors in there. The variable names should be very similar
